version: '3'
services:
    apache:
        image: webdevops/php-apache-dev:ubuntu-18.04 # change tag if necessary
        container_name: apache
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=sample.local # change domain according to needs
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=Europe/Berlin
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M        # stronger machines can use higher value
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - /path/to/magento:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"
        links:
          - mysql
    mysql:
        image: mariadb:10
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root    # change if needed
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
volumes:
    db-data:
        external: false
