version: '3'
services:
  mysql:
    image: mariadb:10.2
    container_name: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
      - ./config/db/my.cnf:/etc/my.cnf
    networks:
      - mysql
networks:
  mysql:
    driver: bridge
